"""initial_schema

Revision ID: b3e3ec2e3343
Revises: 9ab842fdb7fa
Create Date: 2026-06-01 22:46:42.804189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e3ec2e3343'
down_revision: Union[str, Sequence[str], None] = '9ab842fdb7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_active')
    # ### end Alembic commands ###
